name: Deploy Flask App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'tokyo-rider-454306-h6'

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/tokyo-rider-454306-h6/flask-app .
          docker push gcr.io/tokyo-rider-454306-h6/flask-app

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'flask-app-service'
          image: 'gcr.io/tokyo-rider-454306-h6/flask-app'
          region: 'us-central1'
